### ISSUE TITLE
[RFC-01] Manager to create RFC.

### ISSUE THREAD

**Issue by StephYKW** [The-Kumarajiva-Project/Admin#3]
**RFC title**:

**RFJ link**:

**Job manager**: Stephanie 

**Collaborator(s)**: 

## 1. Summary

Copy from RFJ.

## 2. Keyword definitions

Copy definitions from RFJ (section two).
Define any new or important concepts from the detailed approach (section three) of this RFC.

## 3. Detailed approach

Describe the step-by-step approach you will take to doing this job.

## 4. Constraints

Describe any constraints that the client didn’t mention in the RFJ that could affect the outcome of this job.

## 5. Other options

What other options did you consider in your approach to the job? Why didn’t you choose them?

## 6. Risks and risk reduction

What could go wrong with your plan? What can you do to reduce the risks you described?

## 7. Open questions

What do you need to know about this job to complete it?

## 8. Resources

What resources do you need to do this job?

## 9. Definition of acceptable end product

Give a precise, detailed description of the end product. Describe the threshold for what is acceptable and what is not. Include the delivery format, the Kumarajiva Project quality standard for this type of job, etc. 

## 10. Milestones

- [ ] deleted.
- [ ] to learn something
- [ ] step 1
- [ ] step 2

**Comment by StephYKW** [comment]
**RFC title**: T310大寶積經_Mahāratnakūṭasūtra_InterText

**RFJ link**: https://github.com/The-Kumarajiva-Project/Admin/issues/2

**Job manager**: Stephanie 

**Collaborator(s)**: 
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-4ff39d53-7fff-2560-6cbd-fdba12f2c4a3"><div dir="ltr" style="margin-left:0pt;" align="left">

  | Team Member  (Alignment) | Group Leaders  | Consultants 
-- | -- | -- | --
1 | 郭文宇、楊希 | 怡靜 | Karma Palden、Professor Sherab Chen 陳老師
2 | 陳詩彤、Stephanie | 怡靜 | Karma Palden、Professor Sherab Chen 陳老師
3 | 史靜、小莉 | 可書 | Karma Palden、Professor Sherab Chen 陳老師
4 | 王猛、Heidi | 可書 | Karma Palden、Professor Sherab Chen 陳老師


## 1. Summary

Align the Chinese texts with the Tibetan version of the Ratnakuta-sutra.

## 2. Keyword definitions

1. Ratnakuta-sutra: Ratnakuta-sutra (short for Mahāratnakūṭa Sūtra) is the original Sanskrit title of the scripture, but in this project, it is used also to call the corpus of its Tibetan and Chinese canonical translations, and specifically, the [Tibetan version] and Taisho 310 大寶積經
2. Text alignment: In this project, “text alignment” refers to matching Chinese text to corresponding Tibetan text, basically on a sentence level; but if necessary, matching of any two semantic blocks of the two languages.
3. Translation glossary: An index of specific terminology with approved translations in target languages that is agreed and used among translators, here who are engaging in Tibetan to Chinese Buddhist translations. Translation glossaries aid translators in ensuring each time a defined term appears in any language, it is used correctly and consistently.
4. Translation memory: In this project, translation memory refers to quality data of well aligned Tibetan-Chinese Buddhist text segments (on sentence, paragraph or sentence-like unit level), used to produce translation glossaries to aid new (human) Tibetan to Chinese translations.


## 3. Detailed approach

**Project preparation and training**

1. Github tutorials and guidelines for alignment: in both English and Chinese versions.
2. Online project setting and folders naming: for repositories, files, and members accessibility. 
3. Defining team members: team (alignement) members, group leaders, project managers.
4. Github and Inter-text training: see milestones.

**Text alignment** (Followed by bi-weekly project meetings and evaluation and technical Q&A session.)

1. Introduction of Mahāratnakūṭasūtra by Prof. Sherab Chen: to give a global view of the meaning to alignment members.
2. In Progress-Draft: with the tech support from alignment team leaders
3. Review: by team leaders, then Prof. Chen and Karma Palden
4. Finalisation


## 4. Constraints

None.

## 5. Other options

Refer to RFJ 7.

## 6. Risks and risk reduction

1. What could go wrong with your plan?

GitHub and Inter-Text are both new programs to all of our 8 budding translators from Kumarajiva, and will also be new for future upcoming translators, therefore, detailed training needs to be provided to all translators who will be supporting on that project.  GitHub is a shared project platform, we will need to ensure the originality and correctness of all the projects’ files at the Github Repository. If the files may be corrupted, it will impact on the entire working progress, and project efficiency. 

2. What can you do to reduce the risks you described?

According to our current project resources arrangement (8 budding translators, 2 hours/week/person), it is estimated to finish this Tibetan and Chinese Text alignment, it will take up to a minimum of 6 years.  During this extended project implementation time, we will need to have a dedicated project lead to monitor the files integrity and accuracy on a regular basis. It is recommended to have professional technical advice on files protection strategy. 


## 7. Open questions

1. Within The-Kumarajiva-Project - there are 3 repositories. Under repositories - BO-ZH TMs, I have created a project name, “ T310大寶積經_Mahāratnakūṭasūtra_InterText”. Please confirm if this project name is suitable. And If this project name is suitable, in the future for all other new projects that need to be created under the BO-ZH TMs repositories, a new project name and project planning will need to be created separately to avoid confusion of the project planning, and management. 
2. Technical question: How to assign a new project into the same repository?
3. There is 49 chapters within Mahāratnakūṭasūtra, is there any expected timeline to implement the project for all chapters? 
4. Who will be providing Github and Inter-Text training for all the team members? 
5. Who will be available to provide technical support of GitHub and inter-Text if there are any possible technical questions that arise during the training process and implementation process? 
6. If there is any project management transition, is there any project transition protocol set up in place? 
7. How to evaluate and quantify the contributions of the translation projects? Are there any evaluation parameters?  OKRs or KPIs.
8. Is there any existing successful translation glossaries production as our reference in other languages? 
9. Is it possible to invite Professor provide a teaching on Mahāratnakūṭasūtra chapter 2 prior the actual text alignment to start? 

## 8. Resources

Refer to question 7. 

## 9. Definition of acceptable end product

The project quality standard may need to depend on project evaluation parameters which should be set up prior the project start, and being considered thoroughly and implemented into the project daily progress. 

We may start with the project evaluation parameters (OKRs or KPIs) by considering the following aspects: (detail discussion please refer to above items 7 for further information.)

1. Project schedule, efficiency, etc
2. Accuracy of the Tibetan and Chinese matching. 
3. Quantify project success by its number of text? 
4. Publicity of the project in Social media? 

## 10. Milestones

Each of the chapter’s translation need to go through 4 stages: 

1. Project Preparation  項目準備
2. In Progress-Draft-對讀-初稿
3. Review-對讀-檢查
4. Final-終審完成

And we will be starting with Chapter 2 (第二會 - 無邊莊嚴會 - T46 བམ་པོ་དང་པོ། ), and it will be divided into 4 parts, each parts will be lead by different translators. Each of the 49 chapters will go through the above 4 stages. 
Below are the draft project milestones for Chapter 2. 

**26 to 30th September, 2022**

- [ ] Finished the 1st GitHub tutorial in both Chinese and English versions and uploaded into GitHub project - Wiki.  
- [ ] GitHub online project setting and folders naming discussion. 
- [ ] Team meeting to confirm above (File naming, txt final, prepare the .xml. finalize GitHub online set up, milestone ). 
- [ ] Assign a small team for chapter 2 - 4 parts, and team leaders for review.  
- [ ] Finalize RFJ01. 

**3rd to 7th October, 2022**

- [ ] Finalise RFC01.
- [ ] Approve RFC01.
- [ ] Assign the  training schedule and trainers.
- [ ] Create & finalise a Github repository and readme file.
- [ ] Create & finalise a Github project for jobs and work stages and plans. 

**10th to 14th October , 2022 (Workshop preparations)**

- [ ] First week of GitHub and Inter-text training. (Who? When?)
- [ ] Prepare training workshop, announcement  and schedule.

**17th to 28th October, 2022 (Training workshop & Tryouts)**

- [ ] Teaching on Mahāratnakūṭasūtra chapter 2 prior the actual text alignment to start.
- [ ] Practice of Github and Inter-text, including Q&A workshop. Including Create issues, Assign issues, Assign milestones, Do the work and create pull requests, Merge requests
- [ ] Including tryout of all project stages. 
- [ ] Including review of draft text by team leader. 

**31st Oct to 4th November, 2022  (Final workshop and Q&A)**

- [ ] Evaluation of training and technical Q&A. 

**7th Nov onward, 2022**

- [ ] Expecting to start the actual Chapter 2 TIbetan and Chinese Text Alignment work. 
- [ ] Followed by bi-weekly project meetings and evaluation and technical Q&A session.
